# https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html#viewingResponse
# @no-cookie-jar
###

#@no-cookie-jar
GET http://localhost:8080/api/v1/products

###

#@no-cookie-jar
GET http://localhost:8080/api/v1/products
Authorization: Basic baduser password

###

#@no-cookie-jar
GET http://localhost:8080/api/v1/products
Authorization: Basic user badpassword

###

#@no-cookie-jar
GET http://localhost:8080/api/v1/products
Authorization: Basic user password

###

#@no-cookie-jar
GET http://localhost:8080/api/v1/products
Authorization: Basic user2 password
###

